# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mioto_objc' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    source 'https://github.com/CocoaPods/Specs.git'
    
    use_frameworks!
    pod 'MaterialComponents/Snackbar'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
    pod 'SDWebImage'
    pod 'NVActivityIndicatorView'
    
    pod 'FBSDKLoginKit'
    
    platform :ios, '8.0'
    use_frameworks!
    # Pods for Mioto_objc
    
end
